name: 安全检查

on:
    pull_request:
        branches:
            - dev
            - main
    push:
        branches:
            - main
    schedule:
        - cron: '23 3 * * 1'

permissions:
    contents: read

jobs:
    dependency-review:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: 检出代码
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

            - name: 审查依赖变化
              uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
              with:
                  fail-on-severity: high

    codeql:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            security-events: write
        steps:
            - name: 检出代码
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

            - name: 初始化 CodeQL
              uses: github/codeql-action/init@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
              with:
                  languages: javascript-typescript

            - name: 执行 CodeQL 分析
              uses: github/codeql-action/analyze@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
